# Generated by Django 4.2.26 on 2025-12-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
    ]
