# Generated by Django 4.2.26 on 2025-12-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructores'},
        ),
    ]
